//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.details = new HashSet<detail>();
        }
    
        public string product_id { get; set; }
        public string full_name { get; set; }
        public string hard_drive { get; set; }
        public string ram { get; set; }
        public string CPU { get; set; }
        public Nullable<bool> states { get; set; }
        public string color { get; set; }
        public string descriptions { get; set; }
        public string images { get; set; }
        public string date_of_manufacture { get; set; }
        public int total { get; set; }
        public int amount { get; set; }
        public string supplier_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail> details { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
