//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.invoices = new HashSet<invoice>();
        }
    
        public string id { get; set; }
        public string city { get; set; }
        public string last_name { get; set; }
        public string firt_name { get; set; }
        public Nullable<bool> states { get; set; }
        public string date_of_birth { get; set; }
        public string gender { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string position { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string create_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
